// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#include "CryptoUtils.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CPCryptoUtils;

namespace djinni_generated {

class CryptoUtils
{
public:
    using CppType = std::shared_ptr<::cryptoplus::CryptoUtils>;
    using CppOptType = std::shared_ptr<::cryptoplus::CryptoUtils>;
    using ObjcType = CPCryptoUtils*;

    using Boxed = CryptoUtils;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

