// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ec.djinni

#import <Foundation/Foundation.h>
@class CPECCurve;
@class CPECPoint;
@class CPInteger;


@interface CPECCurve : NSObject

+ (nullable CPECCurve *)create:(nullable CPInteger *)p
                             a:(nullable CPInteger *)a
                             b:(nullable CPInteger *)b
                             n:(nullable CPInteger *)n
                             g:(nullable CPECPoint *)g;

+ (nullable CPECCurve *)SECP256K1;

+ (nullable CPECPoint *)getPublicElement:(nonnull NSData *)publicKey;

+ (nullable CPInteger *)getPrivateElement:(nonnull NSData *)privateKey;

- (nullable CPInteger *)getP;

- (nullable CPInteger *)getA;

- (nullable CPInteger *)getB;

- (nullable CPInteger *)getN;

- (nullable CPECPoint *)getG;

- (nullable CPECPoint *)computeGenerator:(nonnull NSData *)seed;

- (nullable CPECPoint *)inv:(nullable CPECPoint *)a;

- (nullable CPECPoint *)add:(nullable CPECPoint *)a
                          b:(nullable CPECPoint *)b;

- (nullable CPECPoint *)sub:(nullable CPECPoint *)a
                          b:(nullable CPECPoint *)b;

- (nullable CPECPoint *)mul:(nullable CPInteger *)a
                          b:(nullable CPECPoint *)b;

- (nullable CPECPoint *)multiply:(nullable CPInteger *)a
                               b:(nullable CPECPoint *)b;

- (BOOL)verify:(nullable CPECPoint *)p;

- (nonnull NSData *)encodePoint:(nullable CPECPoint *)p
                     compressed:(BOOL)compressed;

- (nullable CPECPoint *)decodePoint:(nonnull NSData *)encoded;

@end
