// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ec.djinni

#import "CPECPoint+Private.h"
#import "CPECPoint.h"
#import "CPECCurve+Private.h"
#import "CPInteger+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CPECPoint ()

- (id)initWithCpp:(const std::shared_ptr<::cryptoplus::ECPoint>&)cppRef;

@end

@implementation CPECPoint {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::cryptoplus::ECPoint>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::cryptoplus::ECPoint>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable CPECPoint *)create:(nullable CPInteger *)x
                             y:(nullable CPInteger *)y {
    try {
        auto objcpp_result_ = ::cryptoplus::ECPoint::create(::djinni_generated::Integer::toCpp(x),
                                                            ::djinni_generated::Integer::toCpp(y));
        return ::djinni_generated::ECPoint::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CPInteger *)getX {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getX();
        return ::djinni_generated::Integer::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CPInteger *)getY {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getY();
        return ::djinni_generated::Integer::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setX:(nullable CPInteger *)num {
    try {
        _cppRefHandle.get()->setX(::djinni_generated::Integer::toCpp(num));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setY:(nullable CPInteger *)num {
    try {
        _cppRefHandle.get()->setY(::djinni_generated::Integer::toCpp(num));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)eq:(nullable CPECPoint *)b {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->eq(::djinni_generated::ECPoint::toCpp(b));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CPECPoint *)inv:(nullable CPECCurve *)curve {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->inv(::djinni_generated::ECCurve::toCpp(curve));
        return ::djinni_generated::ECPoint::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CPECPoint *)add:(nullable CPECCurve *)curve
                          b:(nullable CPECPoint *)b {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->add(::djinni_generated::ECCurve::toCpp(curve),
                                                       ::djinni_generated::ECPoint::toCpp(b));
        return ::djinni_generated::ECPoint::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CPECPoint *)sub:(nullable CPECCurve *)curve
                          b:(nullable CPECPoint *)b {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->sub(::djinni_generated::ECCurve::toCpp(curve),
                                                       ::djinni_generated::ECPoint::toCpp(b));
        return ::djinni_generated::ECPoint::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CPECPoint *)mul:(nullable CPECCurve *)curve
                          b:(nullable CPInteger *)b {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->mul(::djinni_generated::ECCurve::toCpp(curve),
                                                       ::djinni_generated::Integer::toCpp(b));
        return ::djinni_generated::ECPoint::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ECPoint::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ECPoint::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CPECPoint>(cpp);
}

}  // namespace djinni_generated

@end
