// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ec.djinni

#import <Foundation/Foundation.h>
@class CPECCurve;
@class CPECPoint;
@class CPInteger;


@interface CPECPoint : NSObject

+ (nullable CPECPoint *)create:(nullable CPInteger *)x
                             y:(nullable CPInteger *)y;

- (nullable CPInteger *)getX;

- (nullable CPInteger *)getY;

- (void)setX:(nullable CPInteger *)num;

- (void)setY:(nullable CPInteger *)num;

- (BOOL)eq:(nullable CPECPoint *)b;

- (nullable CPECPoint *)inv:(nullable CPECCurve *)curve;

- (nullable CPECPoint *)add:(nullable CPECCurve *)curve
                          b:(nullable CPECPoint *)b;

- (nullable CPECPoint *)sub:(nullable CPECCurve *)curve
                          b:(nullable CPECPoint *)b;

- (nullable CPECPoint *)mul:(nullable CPECCurve *)curve
                          b:(nullable CPInteger *)b;

@end
