// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import "CPHashUtils+Private.h"
#import "CPHashUtils.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CPHashUtils ()

- (id)initWithCpp:(const std::shared_ptr<::cryptoplus::HashUtils>&)cppRef;

@end

@implementation CPHashUtils {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::cryptoplus::HashUtils>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::cryptoplus::HashUtils>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSData *)sha256:(nonnull NSData *)message {
    try {
        auto objcpp_result_ = ::cryptoplus::HashUtils::sha256(::djinni::Binary::toCpp(message));
        return ::djinni::Binary::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto HashUtils::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto HashUtils::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CPHashUtils>(cpp);
}

}  // namespace djinni_generated

@end
