// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>


@interface CPHashUtils : NSObject

+ (nonnull NSData *)sha256:(nonnull NSData *)message;

@end
