// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import <Foundation/Foundation.h>
@class CPInteger;


@interface CPInteger : NSObject

+ (nullable CPInteger *)create:(nonnull NSString *)num
                         radix:(int32_t)radix;

+ (nullable CPInteger *)createWithString:(nonnull NSString *)num;

+ (nullable CPInteger *)createWithBinary:(nonnull NSData *)num;

+ (nullable CPInteger *)createWithBinaryString:(nonnull NSString *)num;

+ (nullable CPInteger *)createWithNumber:(int32_t)num;

+ (nullable CPInteger *)ZERO;

+ (nullable CPInteger *)ONE;

+ (nullable CPInteger *)TWO;

+ (nullable CPInteger *)pow2:(int32_t)n;

- (BOOL)eq:(nullable CPInteger *)b;

- (BOOL)gt:(nullable CPInteger *)b;

- (BOOL)gte:(nullable CPInteger *)b;

- (BOOL)lt:(nullable CPInteger *)b;

- (BOOL)lte:(nullable CPInteger *)b;

- (nullable CPInteger *)add:(nullable CPInteger *)b;

- (nullable CPInteger *)sub:(nullable CPInteger *)b;

- (nullable CPInteger *)mul:(nullable CPInteger *)b;

- (nullable CPInteger *)mod:(nullable CPInteger *)n;

- (nullable CPInteger *)inv:(nullable CPInteger *)n;

- (int32_t)compare:(nullable CPInteger *)n;

- (nullable CPInteger *)modMul:(nullable CPInteger *)b
                             n:(nullable CPInteger *)n;

- (nullable CPInteger *)modPow:(nullable CPInteger *)b
                             n:(nullable CPInteger *)n;

- (nullable CPInteger *)modSqrt:(nullable CPInteger *)n;

- (nonnull NSString *)toString;

- (nonnull NSString *)toHex;

- (nonnull NSData *)toBinary;

- (nonnull NSString *)toBinaryString;

- (int32_t)toNumber;

@end
