// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ec.djinni

#import <Foundation/Foundation.h>
@class CPECCurve;
@class CPECPoint;
@class CPInteger;
@class CPKeyPair;


@interface CPKeyPair : NSObject

+ (nullable CPKeyPair *)create:(nullable CPECCurve *)curve;

+ (nullable CPKeyPair *)createWithSeed:(nullable CPECCurve *)curve
                                  seed:(nonnull NSData *)seed;

+ (nullable CPKeyPair *)createWithPrivateKey:(nullable CPECCurve *)curve
                                  privateKey:(nonnull NSData *)privateKey;

- (nullable CPECCurve *)getCurve;

- (nonnull NSData *)getPrivateKey;

- (nonnull NSData *)getPublicKey;

- (nullable CPECPoint *)getPublicElement;

- (nullable CPInteger *)getPrivateElement;

- (BOOL)eq:(nullable CPKeyPair *)b;

@end
