// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#include "RandomUtils.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CPRandomUtils;

namespace djinni_generated {

class RandomUtils
{
public:
    using CppType = std::shared_ptr<::cryptoplus::RandomUtils>;
    using CppOptType = std::shared_ptr<::cryptoplus::RandomUtils>;
    using ObjcType = CPRandomUtils*;

    using Boxed = RandomUtils;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

