// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>


@interface CPUtils : NSObject

+ (nonnull NSString *)binaryToString:(nonnull NSData *)bytes;

+ (nonnull NSString *)binaryToHex:(nonnull NSData *)bytes;

+ (nonnull NSData *)binaryConcat:(nonnull NSData *)a
                               b:(nonnull NSData *)b;

+ (nonnull NSData *)binaryPadZero:(nonnull NSData *)bytes
                           length:(int32_t)length;

+ (nonnull NSData *)stringToBinary:(nonnull NSString *)plainText;

+ (nonnull NSString *)stringToHex:(nonnull NSString *)plainText;

+ (nonnull NSData *)hexToBinary:(nonnull NSString *)hexString;

+ (nonnull NSString *)hexToString:(nonnull NSString *)plainText;

@end
